// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYALxjjscSG3Dez97AZxiFipLCqaR2EAE',
    appId: '1:85067438221:web:2f55f733a4efb0a383eac4',
    messagingSenderId: '85067438221',
    projectId: 'chat-app-95856',
    authDomain: 'chat-app-95856.firebaseapp.com',
    storageBucket: 'chat-app-95856.appspot.com',
    measurementId: 'G-WHGLDHTVKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHF842RA3Zi1_Rtacg3NNKUu_bbW85nMk',
    appId: '1:85067438221:android:4bed86756638536883eac4',
    messagingSenderId: '85067438221',
    projectId: 'chat-app-95856',
    storageBucket: 'chat-app-95856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaBYqwVEzvPaB-_kaZC4qS90sIETn8HgI',
    appId: '1:85067438221:ios:e360e4020bd5514183eac4',
    messagingSenderId: '85067438221',
    projectId: 'chat-app-95856',
    storageBucket: 'chat-app-95856.appspot.com',
    iosClientId: '85067438221-nqmm8hpb81kntnho9nfu643ldn88fd29.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
